name: venera_cli
description: Command-line tool for Venera comic sources.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.12.2

dependencies:
  args: ^2.7.0
  venera_core:
    git:
      url: https://github.com/venera-app/venera_core.git
      ref: d2adfc0dc872ba5de9c504ed5e6ad3f464103259

executables:
  venera: venera

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
